vcf-report: use smart_open crate to enable remote --custom-js-files
rust-bio/rust-bio-tools pull request #153
Opened 2021-05-11 16:47 UTC by dlaehnemann

2021-05-11 17:09 UTC, fxwiegand requested changes
Great idea! Looks good to me. Only one suggestion regarding the newly added test above.

2021-05-12 10:03 UTC, fxwiegand approved these changes
Looks good!

2021-05-12 10:03 UTC, dlaehnemann commented on tests/lib.rs
> +#[test]
For the test, I have now switched to downloading an external `js`-file that is not included among the standard files and check that its content is correct with a local copy in`tests/report/`. That should do the trick, right? Or do you have further suggestions of what to test (inclusion somewhere else?).

2021-05-12 10:05 UTC, fxwiegand commented on tests/lib.rs
> +#[test]
Thats exactly what I had in mind yep! Thanks!

2021-05-12 14:05 UTC, closed without merging