fix: various fixes for consensus calling
rust-bio/rust-bio-tools pull request #191
Opened 2021-10-26 08:55 UTC by FelixMoelder

This PR includes two fixes for consensus read calling:

1. In case of identical base-likelihoods the consensus base will be set to `N`. This lead to an error where no strand could be derived. This is solved by selecting `.` for not available strand information.
2. In some cases the workflow failed when processing complete duplicate groups. This happened due to the occurrence of multiple identical group-IDs. These IDs were created in case of reads containing softclips where there end position differs from the end positions of non softclipping duplicates. This has been solved by building the end position based on read length instead of the cigar.

2021-11-03 11:22 UTC, FelixMoelder commented
In addition there is also a minor improvement to the `verbose-read-names` parameter.
Previously, read names where extended by the indexes of the reads being used for building the consensus read.
While this might be helpful for downstream analysis mapping the consensus reads is not possible in case of paired end data as read names differ.
To solve this the read names will be build based on the query names of the original reads as this results in identical read names shared by pairs.

2021-11-09 12:46 UTC, johanneskoester requested changes

2021-11-09 12:46 UTC, johanneskoester commented on src/bam/collapse_reads_to_fragments/calc_consensus.rs
> +            )
This is a code duplication with above.

2021-11-09 14:39 UTC, FelixMoelder commented on src/bam/collapse_reads_to_fragments/calc_consensus.rs
> +            )
And now it is gone :)

2021-11-09 15:40 UTC, johanneskoester approved these changes

2021-11-09 15:40 UTC, merged