Improve format tag data structure
rust-bio/rust-bio-tools pull request #70
Opened 2020-10-16 09:59 UTC by fxwiegand

This PR improves and simplifies the use of format tags in the custom JS file given by the user. With the lately added interface for multi-sample vcf-files, the `data-format` attribute was not updated. Now format values eg. `OBS` can be dressed in the JS in the the following way: `$(this).data("format")["OBS"][_samplename_]`.

2020-10-20 08:45 UTC, johanneskoester requested changes

2020-10-20 08:45 UTC, johanneskoester commented on src/bcf/report/table_report/create_report_table.rs
> +    }
```suggestion
    let samples = header.samples().iter().map(|s| {
        str::from_utf8(s).map(|s| s.to_owned())
    }).collect::<Result<_, _>>()?;
```

2020-10-26 09:05 UTC, FelixMoelder commented
Just implemented this PR to our [varlociraptor pipeline](https://github.com/snakemake-workflows/dna-seq-varlociraptor/pull/54) and everything works fine now.
I guess we are good to go.

2020-10-26 09:29 UTC, FelixMoelder approved these changes

2020-10-26 09:30 UTC, merged